name: Build

on:
  push:
    branches:
      - main  # Runs on push to dev branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build the application
        run: |
          echo "Building the application..."
          mkdir -p output
          echo "Sample Artifact" > output/artifact.txt

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: output/

      - name: Trigger Deploy Workflow
        run: |
          echo "Triggering deploy workflow..."
        # Deploy workflow will be triggered automatically when `workflow_run` is set in `deploy.yml`
