name: Deploy

on:
  workflow_run:
    workflows: ["Build"]
    types:
      - completed  # Runs only when Build workflow completes successfully

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: build-artifact
          path: deployment/

      - name: Deploy the Application
        run: |
          echo "Deploying the application..."
          cat deployment/artifact.txt
