name: Deploy

on:
  workflow_run:
    workflows: ["Build"]
    types:
      - completed  # Runs only when Build workflow completes successfully

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Download Artifact
        run: |
          BUILD_VERSION=$(gh variable get BUILD_VERSION --json value -q '.value')
          echo "BUILD_VERSION=$BUILD_VERSION" >> $GITHUB_ENV
